version: "3.3"

services:
  db:
    restart: always
    image: postgres
    networks:
      - testing_net
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - .postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=myproject
      - POSTGRES_USER=myprojectuser
      - POSTGRES_PASSWORD=password
  server:
    restart: always
    build: api/
    # command: /bin/bash -c "python tests.py"
    # command: bash -c "sleep infinity"
    # command: ls
    command: bash django-run.sh
    volumes:
      - "./api/goalserver:/usr/src/app/"
    expose:
      - "8000"
    ports:
      - "8000"
    networks:
      - testing_net
    links:
      - db:db
    depends_on:
      - db
    environment:
      - PGHOST=db
      - PGDATABASE=myproject
      - PGUSER=myprojectuser
      - PGPASSWORD=password

volumes:
  postgres_data:

networks:
  testing_net:
    driver: "bridge"
